const data ={
products:[
    {
        _id:'1',
        name: 'Banana Slim Short',
        category:'Shirts',
        image:'/images/p1.jpg',
        price:120,
        brand:'Nike',
        rating: 4.5,
        numReviws: 10,
        description: 'high quality product',
    },
    {
        _id: '2',
        name:'Adidas Slim Shirt',
        category:'Shirts',
        image:'/images/p5.jpg',
        price:90,
        brand:'Adidas',
        rating: 4.0,
        numReviws: 10,
        description: 'high quality product',
    },
    {
        _id: '3',
        name: 'Lacoste Free Shirt',
        category:'Shirts',
        image:'/images/p3.jpg',
        price:220,
        brand:'Lacoste',
        rating: 4.8,
        numReviws: 17,
        description: 'high quality product',
    },
    {
        _id: '4',
        name: 'Nike Slim Pants',
        category:'Pants',
        image:'/images/p1.jpg',
        price:75,
        brand:'Nike',
        rating: 4.5,
        numReviws: 14,
        description: 'high quality product',
    },
    {
        _id: '5',
        name: 'Banana Slim Pants',
        category:'Pants',
        image:'/images/p5.jpg',
        price:120,
        brand:'Banana',
        rating: 4.5,
        numReviws: 10,
        description: 'high quality product',
    },
    {
        _id: '6',
        name: 'Adidas Fit Pants',
        category:'Pants',
        image:'/images/p6.jpg',
        price:130,
        brand:'Adidas',
        rating: 4.5,
        numReviws: 15,
        description: 'high quality product',
    },


],

}
 export default data;